[project]
name = "blog-writer"
version = "0.1.0"
description = "A Blaxel agent that creates blog posts in Notion"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "blaxel>=0.0.73",
    "langchain-openai>=0.3.0,<0.4.0",
    "notion-client>=2.0.0",
]

[tool.hatch.build.targets.wheel]
packages = ["src"]

[dependency-groups]
dev = [
    "ruff>=0.8.2",
]

[tool.ruff]
indent-width = 4

[tool.ruff.format]
indent-style = "space"
quote-style = "double"
skip-magic-trailing-comma = false

[tool.ruff.lint]
select = ["E", "F"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
