apiVersion: blaxel.ai/v1alpha1
kind: IntegrationConnection
metadata:
  name: dall-e-integration
spec:
  integration: dall-e
  secret:
    apiKey: "${secrets.OPENAI_API_KEY}"
---
apiVersion: blaxel.ai/v1alpha1
kind: Function
metadata:
  displayName: dall-e
  name: dall-e
spec:
  integrationConnections:
    - dall-e-integration
  runtime:
    type: mcp
